use anyhow::Error;

pub async fn execute_log(name: &str) -> Result<(), Error> {
    todo!("log")
}
