use anyhow::Error;

pub async fn execute_tail(name: &str) -> Result<(), Error> {
    todo!()
}
